version: '3.3'

services:

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=STORE
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    #env_file:
    #  - docker.env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlos@mail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '5050:80'
    depends_on:
      - postgres

  mysql:
    image: mysql:5
    restart: always
    environment:
      - MYSQL_DATABASE=STORE
      #- MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
    #env_file:
    #  - docker.env
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db
  express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      depends_on:
        - mongo
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
        ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

